### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rohan-deshpande** [creativelifeform/three-particle-designer#5]
- [x] Create base UI layout
- [x] Create toolbar, layers, stage and particle system properties UI
- [x] Create emitter property controllers
    - [x] `Name`
    - [x] `TotalEmitTimes`
    - [x] `Life`
    - [x] `Rate`
    - [x] `Position`
    - [x] `Rotation`
- [x] Create initialiser property controllers
  - [x] `BodySprite`
  - [x] `Life`
  - [x] `Mass`
  - ~`Position`~ Descoped, moved into #13 
  - [x] `Radius`
  - [x] `Rate`
  - [x] `RadialVelocity`
  - [x] `VectorVelocity`
  - [x] `PolarVelocity`
- [x] Create behaviour property controllers
  - [x] `Alpha`
  - [x] `Attraction`
  - [x] `Color`
  - ~`CrossZone`~ Descoped, can't be done until #13 is completed
  - [x] `Force`
  - [x] `Gravity`
  - [x] `RandomDrift`
  - [x] `Repulsion`
  - [x] `Rotate`
  - [x] `Scale`
  - [x] `Spring`
- [x] Enable adding/removing emitters
- [x] Enable adding/removing particle initialisers to an emitter
- [x] Enable adding/removing particle behaviours to an emitter
- [x] Enable cloning particle initialisers from one emitter to another
- [x] Enable cloning particle behaviours from one emitter to another
- [x] Add the ability to enable/disable initializers
- [x] Add the ability to enable/disable behaviours
- [x] Add camera controls
  - [x] Add camera property controls 
  - [x] Add camera reset control
  - [x] Add camera lock control
  - ~Add camera type switcher so an Orthographic camera can be used~ (Descoped, see #17)
- [x] Split properties into tabs
- [x] Add the ability to rename projects
